[phases.setup]
nixPkgs = ["nodejs_24", "python3", "gcc", "gnumake", "fontconfig", "noto-fonts", "noto-fonts-arabic"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[start]
cmd = "bash start.sh"

[variables]
NIXPACKS_NODE_VERSION = "24"
